# Generated by Django 5.0.4 on 2024-04-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_master',
            old_name='standing_arresars',
            new_name='standing_arrears',
        ),
        migrations.RemoveField(
            model_name='content_master',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='content_master',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='course_contents',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='course_contents',
            name='topic',
        ),
        migrations.AddField(
            model_name='content_master',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic_master'),
        ),
        migrations.AddField(
            model_name='course_contents',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic_master'),
        ),
        migrations.AlterField(
            model_name='course_content_feedback',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic_master'),
        ),
        migrations.AlterField(
            model_name='courses_master',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic_master'),
        ),
        migrations.AlterField(
            model_name='question_master',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic_master'),
        ),
    ]
