# Generated by Django 5.0.3 on 2024-04-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_standing_arresars_candidate_master_standing_arrears_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_contents',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses_master'),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
