# Generated by Django 5.0.3 on 2024-04-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_contents_course_id_alter_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests_candidates_answers',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_master'),
        ),
    ]
